### ISSUE TITLE
refactor the conditionals in the JobList component

### ISSUE THREAD

**Issue by natevenn** [LookingForMe/lookingForFrontEnd#17]
there is a conditional that waits for the jobs to be loaded in the JoblList component. Theoretically, Jobs should already be defined. Figure out why its undefined and how to eliminate the conditional.

**Comment by ksk5280** [comment]
Jobs is empty until after the ajax call is hit, which is why the conditional is required, so I think that we can close this issue. Thoughts? @natevenn

**Comment by cheljoh** [comment]
Going to close issue, next group can tackle if they wish.
