### ISSUE TITLE
Show all the jobs

### ISSUE THREAD

**Issue by ksk5280** [LookingForMe/lookingForFrontEnd#18]
We are only showing the first 25 jobs, but we should show all the jobs. Investigate how to do this through pagination or infinite scrolling.

**Comment by cheljoh** [comment]
I was curious about this and figured it had something to do with the pagination. If you want to show more pages, you have to add extra parameters- `http://lookingforme.herokuapp.com/api/v1/jobs?page=192`. As of today, there were 192 pages (so quite a lot of results). Is it worthwhile to show so many results, or work instead on searching by location, stack, etc?
