### ISSUE TITLE
change all files to PascalCase and all components to .jsx

### ISSUE THREAD

**Issue by natevenn** [LookingForMe/lookingForFrontEnd#40]
currently we have a mix of uppercase and lowercase letters in our file names. 
change all files to lowercase

**Comment by cheljoh** [comment]
When Kimi and I looked up naming conventions for React files, many had uppercase letters. Worth looking into?

**Comment by natevenn** [comment]
Ok I just looked up naming conventions and it does look like PascalCase for file extensions and using .jsx for component files
