### ISSUE TITLE
Split SearchBarAndListings

### ISSUE THREAD

**Issue by s-espinosa** [LookingForMe/lookingForFrontEnd#60]
Seems that searching and displaying results are related but separate activities. Could we refactor to pass information from the search bar to the display through a common parent? Will need some additional research to see if there are any technical barriers to implementation.

**Comment by jeneve** [comment]
## @s-espinosa, @jdliss here are my thoughts so far in looking into this issue:

- the SearchBar  & the JobsListings the  are already 2 components, but the JobsListings is a child of the SearchBarAndListings. SearchBarAndLIstings is a child of JobsIndex. Right now JobsIndex doesn't do anything except render it's child (SearchBarAndListings) and remember the active page (not 100% sure what this means yet.) SearchBarAndListings sends data down to it's child- this is a good pattern, right?

- in my understanding of this **pivot** the new situation will be that the SearchBar and the JobsListings will be siblings with JobsIndex as the parent. the SearchBar will send events up to the JobsIndex, which will then trigger updating and send data down to the JobsListings. Is this a better pattern? 

- **things that would need to change:** JobsIndex would need to hold all of the state that SearchBarAndJobsListings does now, and would send that data down to JobsListings. SearchBar would emit events on update to it's input field that would trigger changes in JobsIndex and update JobsListings.  Does that sound about right to y'all?
