### ISSUE TITLE
Links to Job Postings Broken

### ISSUE THREAD

**Issue by s-espinosa** [LookingForMe/lookingForFrontEnd#71]
When you click on a link to view a job posting on an external site, the app takes you back to the main page instead of to the external link. The link is captured in the address bar, but a link to our application precedes it, and causes our root page to render.

The ability to visit external links was working previously. However, when we changed the router in [PR 70](https://github.com/LookingForMe/lookingForFrontEnd/pull/70) it appears we broke it.

May need to determine how to use external links when using hashHistory, or potentially revisit alternatives to hashHistory to respond to [issue 63](https://github.com/LookingForMe/lookingForFrontEnd/issues/63). Research on that issue may provide alternatives, particularly [this link](https://www.themarketingtechnologist.co/react-router-an-introduction/).

**Comment by rrgayhart** [comment]
BELONGS TO BRIAN

**Comment by saylerb** [comment]
In my attempt to replicate this issue, I discovered that the changes made in #63 seem to have broken navigation to the detail page when running the application locally.  This is preventing me from replicating this issue (#71) when running locally.  When running locally and I click "view detail", the app hangs and shows "Loading..." I narrowed this down to the the render method in the `JobShow` component, which is in turn is supposed to render the `JobDetail` component. [It's specifically hitting this line](https://github.com/LookingForMe/lookingForFrontEnd/blob/master/lib/components/JobShow.js#L27)

What's interesting is that I can't reproduce this in the production app, where clicking "view detail" is working fine, but trying to navigate the external job listing is broken.

**Comment by saylerb** [comment]
I'm having trouble replicating issue #63 

So I discovered when removing hashHistory, running webpack-dev-server by `npm run dev` that the app seems to properly render the detail page AND properly opens a new tab to the external job posting when clicking "view job posting."  

It also seems to work correctly if I run `npm run build` and `npm start`. So maybe it was a build issue, and not a routing issue? I'll keep looking into this.

**Comment by saylerb** [comment]
Robbie and I successfully replicated the issue #63 this afternoon.
