### ISSUE TITLE
Replace jQuery AJAX requests with promises

### ISSUE THREAD

**Issue by saylerb** [LookingForMe/lookingForFrontEnd#76]
Suggesting that we don't mix jQuery into the project, if the only reason is to make GET requests to the API.

**Comment by zackforbing** [comment]
with the merge of Brian's PR (#77) I think this can be safely closed, but we have not pulled jQuery out wholesale. it is still a dependency, although I am not sure with axios functional if it is necessary at all.

**Comment by saylerb** [comment]
@zackforbing jQuery is a dependency of stock boostrap. But if you use React-boostrap (which is already in the project dependencies), you should be able to take out the jQuery CDN import in the HTML file. The only thing you'd need to import in from CDN file
